const regex = /(:\)|:\(|:D|;\)|:P|:O|:\||:\/|:3|;\(|:\*|XD|:'\)|>: \(|8\)|8\(|:\]|:\}|:{|:\\|:s|:\$|:#|:x|:!|:\^ \)|:smirk:|:heart:|:star:|:exclamation:|:question:|:arrow_up:|:arrow_down:|:arrow_left:|:arrow_right:|:ok_hand:|:thumbsup:|:thumbsdown:|:clap:|:pray:|:muscle:|:poop:|:bomb:|:fire:|:100:)/g
// Regular expression to match common emojis
const unicodeEmojis = {
    ":)": String.fromCodePoint(0x1F600),
    ":(": String.fromCodePoint(0x1F62D),
    ":D": String.fromCodePoint(0x1F603),
    ";)": String.fromCodePoint(0x1F609),
    ":P": String.fromCodePoint(0x1F61B),
    ":O": String.fromCodePoint(0x1F62E),
    ":|": String.fromCodePoint(0x1F610),
    ":/": String.fromCodePoint(0x1F615),
    ":3": String.fromCodePoint(0x1F63A),
    ";(": String.fromCodePoint(0x1F622),
    ":*": String.fromCodePoint(0x1F617),
    "XD": String.fromCodePoint(0x1F606),
    ":')": String.fromCodePoint(0x1F602),
    ">:(": String.fromCodePoint(0x1F620),
    "8)": String.fromCodePoint(0x1F60E),
    "8(": String.fromCodePoint(0x1F623),
    ":]": String.fromCodePoint(0x1F60A),
    ":}": String.fromCodePoint(0x1F60A),
    ":{": String.fromCodePoint(0x1F641),
    ":/": String.fromCodePoint(0x1F615),
    ":\\": String.fromCodePoint(0x1F615),
    ":s": String.fromCodePoint(0x1F616),
    ":$": String.fromCodePoint(0x1F633),
    ":#": String.fromCodePoint(0x1F645),
    ":x": String.fromCodePoint(0x1F636),
    ":!": String.fromCodePoint(0x1F631),
    ":^)": String.fromCodePoint(0x1F60F),
    ":smirk:": String.fromCodePoint(0x1F60F),
    ":heart:": String.fromCodePoint(0x2764),
    ":star:": String.fromCodePoint(0x2B50),
    ":exclamation:": String.fromCodePoint(0x2757),
    ":question:": String.fromCodePoint(0x2753),
    ":arrow_up:": String.fromCodePoint(0x2B06),
    ":arrow_down:": String.fromCodePoint(0x2B07),
    ":arrow_left:": String.fromCodePoint(0x2B05),
    ":arrow_right:": String.fromCodePoint(0x27A1),
    ":ok_hand:": String.fromCodePoint(0x1F44C),
    ":thumbsup:": String.fromCodePoint(0x1F44D),
    ":thumbsdown:": String.fromCodePoint(0x1F44E),
    ":clap:": String.fromCodePoint(0x1F44F),
    ":pray:": String.fromCodePoint(0x1F64F),
    ":muscle:": String.fromCodePoint(0x1F4AA),
    ":poop:": String.fromCodePoint(0x1F4A9),
    ":bomb:": String.fromCodePoint(0x1F4A3),
    ":fire:": String.fromCodePoint(0x1F525),
    ":100:": String.fromCodePoint(0x1F4AF)
} // Map of Unicode emojis for each matched emoji

export { regex, unicodeEmojis }